# Generated by Django 2.0.2 on 2019-03-05 17:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TOBC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='用户答案')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='作答时间')),
            ],
            options={
                'verbose_name': '用户做题记录',
                'verbose_name_plural': '用户做题记录',
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='总分')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='录入时间')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOBC.PaperList', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '用户总分',
                'verbose_name_plural': '用户总分',
            },
        ),
    ]
