# Generated by Django 2.0.2 on 2019-03-05 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TOBC', '0002_auto_20190305_1716'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='useranswerlog',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOBC.CourseList', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='useranswerlog',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOBC.Paper', verbose_name='试卷'),
        ),
        migrations.AddField(
            model_name='useranswerlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
