# Generated by Django 2.0.2 on 2019-03-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190305_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='danwei',
            field=models.CharField(default='', max_length=50, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='leibie',
            field=models.CharField(default='', max_length=50, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='nickname',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='zhiwu',
            field=models.CharField(default='', max_length=50, verbose_name='职务'),
        ),
    ]
