# Generated by Django 2.0.2 on 2019-03-05 17:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='科目名')),
                ('decs', models.CharField(default='', max_length=500, verbose_name='科目说明')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '考试科目',
                'verbose_name_plural': '考试科目',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '试题列表',
                'verbose_name_plural': '试题列表',
            },
        ),
        migrations.CreateModel(
            name='PaperCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField(verbose_name='题目')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '试题临时列表',
                'verbose_name_plural': '试题临时列表',
            },
        ),
        migrations.CreateModel(
            name='PaperList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='试卷名')),
                ('is_allow', models.BooleanField(default=False, verbose_name='是否启用')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOBC.CourseList', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '试卷列表',
                'verbose_name_plural': '试卷列表',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(choices=[('xz', '选择题'), ('pd', '判断题'), ('zg', '问答')], default='xz', max_length=2, verbose_name='题目类型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('answer', models.TextField(verbose_name='正确答案')),
                ('choice_a', models.TextField(default='A.', verbose_name='A选项')),
                ('choice_b', models.TextField(default='B.', verbose_name='B选项')),
                ('choice_c', models.TextField(default='C.', verbose_name='C选项')),
                ('choice_d', models.TextField(default='D.', verbose_name='D选项')),
                ('score', models.IntegerField(default=0, verbose_name='分值')),
                ('note', models.TextField(default='问答题在此处做答', verbose_name='备注信息')),
                ('boolt', models.TextField(default='True', verbose_name='判断正误正确选项')),
                ('boolf', models.TextField(default='False', verbose_name='判断正误错误选项')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOBC.CourseList', verbose_name='考试科目')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
            },
        ),
    ]
