# Generated by Django 2.0.2 on 2019-03-05 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TOBC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papercache',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='paper',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TOBC.CourseList', verbose_name='所属课程'),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOBC.PaperList', verbose_name='试卷名称'),
        ),
        migrations.AddField(
            model_name='paper',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOBC.Question', verbose_name='题目'),
        ),
    ]
