# Generated by Django 2.0.2 on 2019-03-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBC', '0002_auto_20190305_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_e',
            field=models.TextField(default='E.', verbose_name='E选项'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_f',
            field=models.TextField(default='F.', verbose_name='F选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('xz', '选择题'), ('pd', '判断题'), ('mxz', '多选')], default='xz', max_length=4, verbose_name='题目类型'),
        ),
    ]
