# Generated by Django 2.0.2 on 2019-03-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBC', '0003_auto_20190318_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='boolf',
            field=models.TextField(default='错', verbose_name='判断正误错误选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='boolt',
            field=models.TextField(default='对', verbose_name='判断正误正确选项'),
        ),
    ]
