# Generated by Django 2.0.2 on 2019-03-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBC', '0004_auto_20190319_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_num',
            field=models.IntegerField(default=4, verbose_name='选项数'),
        ),
    ]
